### ISSUE TITLE
Is it possible to use pgx for postgres?

### ISSUE THREAD

**Issue by cemremengu** [bokwoon95/sq#1]
I would like to replace pq with pgx. Is it possible or would you consider a PR to replace pq?

**Comment by bokwoon95** [comment]
sq doesn't depend on pq directly, or any other database driver in fact. As long as you import [pgx through database/sql](https://github.com/jackc/pgx/wiki/Getting-started-with-pgx-through-database-sql) it should work no matter if you're using pgx, pq or even mysql. 

Example you can try yourself:

```go
package main

import (
    "database/sql"
    "fmt"
    "log"
    "os"

    "github.com/bokwoon95/sq"
    _ "github.com/jackc/pgx/v5/stdlib" // if you are using pgx
    // _ "github.com/lib/pq"              // if you are using pq
    // _ "github.com/go-sql-driver/mysql" // if you are using mysql
)

func main() {
    db, err := sql.Open("pgx", os.Getenv("DATABASE_URL"))
    if err != nil {
        log.Fatal(err)
    }
    nums, err := sq.FetchAll(sq.Log(db), sq.
        Queryf("SELECT {*} FROM (VALUES (1), (2), (3)) AS t (num)"),
        func(row *sq.Row) (int, error) {
            return row.Int("t.num"), nil
        },
    )
    fmt.Println(nums)
}
```

**Comment by cemremengu** [comment]
Thank you! Great work by the way I was looking for an implememtation like jooq.
