### ISSUE TITLE
Docs incomplete probably.

### ISSUE THREAD

**Issue by HonestCodeWasTaken** [bokwoon95/sq#10]
a := sq.New[models.ACTOR]("a")
		actors, err := sq.FetchAll(lr.Db, sq.
			From(a).
			Where(a.FIRST_NAME.EqString("DAN")).
			SetDialect(sq.DialectPostgres),
			func(row *sq.Row) Actor {
				return Actor{
					ActorID:   row.IntField(a.ACTOR_ID),
					FirstName: row.StringField(a.FIRST_NAME),
					LastName:  row.StringField(a.LAST_NAME),
				}
			},
		)
		
		package models

import (
	"database/sql"
	"time"

	"github.com/bokwoon95/sq"
)

type ACTOR struct {
	sq.TableStruct `sq:"Actor"`
	ACTOR_ID       sq.NumberField `sq:"ActorID"`
	FIRST_NAME     sq.StringField `sq:"FirstName"`
	LAST_NAME      sq.StringField `sq:"LastName"`
	LAST_UPDATE    sq.TimeField   `sq:"LastUpdate"`
}

undefined: Actorcompiler[UndeclaredName](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#UndeclaredName)

trying to change it to something else leads to:

cannot use row.IntField(a.ACTOR_ID) (value of type int) as sq.NumberField value in struct literalcompiler[IncompatibleAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#IncompatibleAssign)

		a := sq.New[models.ACTOR]("a")
		actors, err := sq.FetchAll(lr.Db, sq.
			From(a).
			Where(a.FIRST_NAME.EqString("DAN")).
			SetDialect(sq.DialectPostgres),
			func(row *sq.Row) models.ACTOR {
				return models.ACTOR {
					ACTOR_ID:   row.IntField(a.ACTOR_ID),
					FirstName: row.StringField(a.FIRST_NAME),
					LastName:  row.StringField(a.LAST_NAME),
				}
			},
		)
		
		
		
docs seem confusing and i cant figure out how to properly fetch something

**Comment by bokwoon95** [comment]
Hi, you might be missing the definition of `type Actor struct`. There should be two structs like this

```go
// Table struct (represents your SQL table).
type ACTOR struct {
	sq.TableStruct sq:"Actor"
	ACTOR_ID       sq.NumberField sq:"ActorID"
	FIRST_NAME     sq.StringField sq:"FirstName"
	LAST_NAME      sq.StringField sq:"LastName"
	LAST_UPDATE    sq.TimeField   sq:"LastUpdate"
}

// Model struct (represents an instance of an actor).
type Actor struct {
	ActorID    int
	FirstName  string sq:"FirstName"
	LastName   string sq:"LastName"
	LastUpdate time.Time  sq:"LastUpdate"
}

// Note the different casing of ACTOR vs Actor.
a := sq.New[ACTOR]("a")
actors, err := sq.FetchAll(lr.Db, sq.
	From(a).
	Where(a.FIRST_NAME.EqString("DAN")).
	SetDialect(sq.DialectPostgres),
	func(row *sq.Row) Actor {
		return Actor{
			ActorID:   row.IntField(a.ACTOR_ID),
			FirstName: row.StringField(a.FIRST_NAME),
			LastName:  row.StringField(a.LAST_NAME),
		}
	},
)
```

**Comment by HonestCodeWasTaken** [comment]
Can you please update the docs to show that example you just posted? Otherwise it's a little bit unclear.

https://bokwoon.neocities.org/sq#querybuilder

**Comment by bokwoon95** [comment]
Ohh, I see what you mean. I'll add it in the docs
