### ISSUE TITLE
Any helpers for handling many 2 many relations?

### ISSUE THREAD

**Issue by KenjiTakahashi** [bokwoon95/sq#12]
Did not see anything in the docs, but thought I'd ask before going the DIY route and handling the join tables manually.

**Comment by bokwoon95** [comment]
Hi, what are you expecting to see when you say you're looking for something that handles many to many relations? 

I'm confused because pulling in tables should always be done with joins, no matter whether the relationship is one to one/one to many/many to many.

**Comment by KenjiTakahashi** [comment]
True, what is specific to many to many scenario is that you need an artificial "join table" with IDs from both sides of the relation.
Some of the ORM-ish libraries abstract that away from the caller. So you specify somehow that relation between table A and B is many to many. Then when the tables are created, the join table gets created implicitly. And when creating queries, it also gets "injected" implicitly into JOINs between A and B. Something like that :-).

I get that `sq` is not supposed to be a full-on ORM, so it's fine if that's not provided. Just asking.

**Comment by KenjiTakahashi** [comment]
Fair enough, thanks for the confirmation!
