### ISSUE TITLE
Docs code for setting global dialect doesn't compile

### ISSUE THREAD

**Issue by KenjiTakahashi** [bokwoon95/sq#13]
The docs say that it can be done with following code
```go
sq.DefaultDialect.Store(&sq.DialectPostgres)
```
but it doesn't work, because
```
invalid operation: cannot take address of sq.DialectPostgres (untyped string constant "postgres")
```
Which is a fairly common Go "gotcha" ;-).

Can be mitigated with
```go
    d := sq.DialectPostgres
    sq.DefaultDialect.Store(&d)
```
It is not as "pleasant", though.

**Comment by bokwoon95** [comment]
Thanks for pointing it out, I didn't notice it because I always set the dialect per-query (I also didn't know constants couldn't be addressed up til now). I'll update the docs with a note.

It's a little clunky, but at least it's only set once in an init function so hopefully not too bad.
