### ISSUE TITLE
MariaDB RETURNING support

### ISSUE THREAD

**Issue by mdigger** [bokwoon95/sq#4]
How do I add "RETURNING" support for MariaDB? Introduce a separate dialect?

**Comment by bokwoon95** [comment]
No, the easiest thing would be to allow the MySQL dialect to also do RETURNING. We can't tell whether the actual database is MySQL or MariaDB, but the database will throw back an error if it's not supported. Looking at MariaDB docs, only INSERT and DELETE support RETURNING?

**Comment by bokwoon95** [comment]
Can you check out the [returning](https://github.com/bokwoon95/sq/tree/returning) branch and see if it works for you?

**Comment by bokwoon95** [comment]
This has been merged into the main branch, check out v0.2.9
